import { motion } from "framer-motion";
import { getSession } from "next-auth/react";
import Head from "next/head";

import DetailsFeed from "../../components/DetailsFeed";
import SignIn from "../../components/SignIn";
import { Movie } from "../../typings";
import requests from "../../utils/requests";

type Props = {
  netflixOriginals: Movie[];
  session: any;
};

function Details({ netflixOriginals, session }: Props) {
  // Skip authentication check for demo
  // if (!session) return <SignIn />;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.designbust.com/download/1037/png/netflix_logo_png_transparet512.png"
        />
      </Head>
      <DetailsFeed netflixOriginals={netflixOriginals} />
    </motion.div>
  );
}

export default Details;

export const getServerSideProps = async (context: any) => {
  // Create mock session to bypass authentication
  const mockSession = {
    user: {
      name: "Demo User",
      email: "demo@netflix.com",
      image: "https://i.imgur.com/HeIi0wU.png",
      username: "demouser",
      uid: "demo-uid-12345"
    }
  };
  
  const [netflixOriginals] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
  ]);

  return {
    props: {
      netflixOriginals: netflixOriginals.results,
      session: mockSession,
    },
  };
};
