import { motion } from "framer-motion";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";

import MainPage from "../components/MainPage";
import SignIn from "../components/SignIn";
import { Movie } from "../typings";
import cachedRequests from "../utils/apiWithCache";

type Props = {
  netflixOriginals: Movie[];
  trendingNow: Movie[];
  topRated: Movie[];
  actionMovies: Movie[];
  comedyMovies: Movie[];
  horrorMovies: Movie[];
  romanceMovies: Movie[];
  documentaries: Movie[];
};

export default function Home({
  netflixOriginals,
  trendingNow,
  topRated,
  actionMovies,
  comedyMovies,
  horrorMovies,
  romanceMovies,
  documentaries,
}: Props) {
  const session = useSession();
  // Temporarily bypass authentication to show movies directly
  // if (!session.data) return <SignIn />;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.designbust.com/download/1037/png/netflix_logo_png_transparet512.png"
        />
      </Head>
      <MainPage
        netflixOriginals={netflixOriginals}
        trendingNow={trendingNow}
        topRated={topRated}
        actionMovies={actionMovies}
        comedyMovies={comedyMovies}
        horrorMovies={horrorMovies}
        romanceMovies={romanceMovies}
        documentaries={documentaries}
        session={null}
      />
    </motion.div>
  );
}

export const getServerSideProps = async (context: any) => {
  try {
    const session = await getSession(context);

    const [
      netflixOriginals,
      trendingNow,
      topRated,
      actionMovies,
      comedyMovies,
      horrorMovies,
      romanceMovies,
      documentaries,
    ] = await Promise.all([
      cachedRequests.fetchNetflixOriginals().catch(() => ({ results: [] })),
      cachedRequests.fetchTrending().catch(() => ({ results: [] })),
      cachedRequests.fetchTopRated().catch(() => ({ results: [] })),
      cachedRequests.fetchActionMovies().catch(() => ({ results: [] })),
      cachedRequests.fetchComedyMovies().catch(() => ({ results: [] })),
      cachedRequests.fetchHorrorMovies().catch(() => ({ results: [] })),
      cachedRequests.fetchRomanceMovies().catch(() => ({ results: [] })),
      cachedRequests.fetchDocumentaries().catch(() => ({ results: [] })),
    ]);

    return {
      props: {
        netflixOriginals: netflixOriginals?.results || [],
        trendingNow: trendingNow?.results || [],
        topRated: topRated?.results || [],
        actionMovies: actionMovies?.results || [],
        comedyMovies: comedyMovies?.results || [],
        horrorMovies: horrorMovies?.results || [],
        romanceMovies: romanceMovies?.results || [],
        documentaries: documentaries?.results || [],
      },
    };
  } catch (error) {
    console.error('Error fetching data:', error);
    return {
      props: {
        netflixOriginals: [],
        trendingNow: [],
        topRated: [],
        actionMovies: [],
        comedyMovies: [],
        horrorMovies: [],
        romanceMovies: [],
        documentaries: [],
      },
    };
  }
};